default['tomcat7']['version'] = "7.0.39"
default['tomcat7']['installDir'] = "/usr/share/tomcat7"
default['tomcat7']['username'] = "admin"
default['tomcat7']['password'] = "admin"
default['tomcat7']['logDir']   = "/var/log/tomcat7"
